### ISSUE TITLE
Other dataset

### ISSUE THREAD

**Issue by 503744434** [feiyuhuahuo/Anomaly_Prediction#12]
Hi! Thanks for your work! And I have to questions.
First, what I want to ask is that if I want to test in other dataset, such as Mall, what should I do?
And second, if I want to taste to make a new dataset, how should I label it?
Looking forward to your reply, thank you again.

**Comment by feiyuhuahuo** [comment]
1. You can download the ped2 dataset to see the  directory structure and prepare Mall like it. Then modify `share_config['data_root']` in `config.py`, and modify the assertion:
![image](https://user-images.githubusercontent.com/32631344/98059293-b3bc2b00-1e81-11eb-9f66-e1477c34b588.png)
Then you can test without training by: `python evaluate.py --dataset=mall --trained_model=choose-a-wieght`. You can also train your dataset first.
2. Since this is an unsupervised network, if you don't need to test, you can directly train with normal videos.
If you want to test during training, you need to label your abnormal videos. You can consult `Label_loader.load_uscd_avenue` to prepare you gt label.
If I have time, I will update this project to support training custom dataset.

**Comment by 503744434** [comment]
Thanks for your help, and I'll taste to do it.

**Comment by 503744434** [comment]
Sorry to bother you again. I found that the format of the .mat file of the MALL dataset was different from that the format of the .mat file of the UCSD dataset, as shown in Figure 1 and Figure 2 respectively. In this case, how do I modify the `Label_loder.load_ucsd_avenue` to load correctly?
![CCEB1D77704C62D9AD7CF203AC8BAE81](https://user-images.githubusercontent.com/46125345/98247281-68ec0180-1fae-11eb-8147-0c498d8085c5.jpg)
![E63A759705C8A267AACFE7DB553D45D3](https://user-images.githubusercontent.com/46125345/98247389-8d47de00-1fae-11eb-897f-e7e58930931f.jpg)

**Comment by feiyuhuahuo** [comment]
Ped2 has only one abnormal event in each test video, so you'd better download the avenue dataset and take a look the `avenue.mat`. 
![image](https://user-images.githubusercontent.com/32631344/98317524-9e790500-2017-11eb-889d-b6f085050f42.png)
This is the `avenue.mat`. In this image, `abnormal_events` contains 21 arrays which are related to the 21 test videos in avenue dataset. The first row  and the second row represents the start frame and the end frame of an abnormal event. So for the first array, there are five abnormal events: from 78 to 120, from 392 to 422, from 503 to 666, from 868 to 910 and from 932 to 1101. You can prepare your code to ensure `abnormal_events` can get your label with the same format.
